---
title: "7_variant_calling_atac"
---

Going to utilize Monopogen for variant call 

# Install Monopogen

Creating a conda env 
```{bash}
cd /projectnb/paxlab/presh

module load miniconda 

conda create -n monopogen_env python=3.8

git clone https://github.com/KChen-lab/Monopogen.git
cd Monopogen

conda activate monopogen_env
pip install -e .


```

I get this warning: 
DEPRECATION: Legacy editable install of Monopogen==1.0.0 from file:///projectnb/paxlab/presh/Monopogen (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  
But looks like it installed so I will move ahead for now. 
  
  
Other packages to load -    
  
!Note We have put the binary compatibility tools including samtools, bcftools, beagle in the app folder. We fixed the version because the output formats vary a lot with different versions. If you are not able to run them, you can compile them in you system. We only test on these tools on following versions:
  
What they recommend - 
samtools Version: 1.2 (using htslib 1.2.1)
bcftools Version: 1.8 (using htslib 1.8)
beagle.27Jul16.86a.jar (version 4.1)
tabix Version: 1.9
bgzip Version: 1.9

  
  
bcftools: error while loading shared libraries: libbz2.so.1.0: not able to open shared object file: No such file or directly
Adding the apps folder of Monopogen in your library environment

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/projectnb/paxlab/presh/Monopogen/apps

AssertionError: Program vcftools cannot be found!
You may set the read/write permission on the folder xx/apps as

chmod 770 -R  /xx/apps
  
```{bash }

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/projectnb/paxlab/presh/Monopogen/apps
```

  
  
```{bash}
path="/projectnb/paxlab/presh/Monopogen"  # where Monopogen is downloaded
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps
python ${path}/src/Monopogen.py  preProcess --help
```



First I need to convert bed to bam file to run the tool!
```{r}
cd /projectnb/paxlab/presh/Data/hg38_resources

https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta
https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta.fai
```


```{bash}
module load bedtools
bedToBam -i input.bed -g genome.txt > output.bam

cd /projectnb/paxlab/presh/Data/variant_calling
bedtools bedtobam -i /projectnb/paxlab/presh/Data/deepseq.fragments.sort.filtered.bed -g /projectnb/paxlab/presh/Data/hg38_resources/Homo_sapiens_assembly38.fasta
```



This doesn't work, we can't work our way back from fragments file to bam file!!!!

Need bam or fastq file 


# Lowseq fastq files

Date: Nov 10 2025 

Starting with trimming lowseq fastq files and aligning them to get bam!

using this as reference: https://github.com/atlasxomics/ATX_epigenomics/tree/2af49aa081c5846ccc9fe1b868d4982430feed5c/fastq2frags

And Yeting's scripts as reference located here: /projectnb/paxlab/Projects/CodeSpaghetti/src/00_fastq2frags


## Finding  hg38 ref 
```{bash}
cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/
conda create --prefix /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/chromap_env  python=3.9
conda activate /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/chromap_env      
conda install -c bioconda -c conda-forge chromap

cd /projectnb/paxlab/Projects/CodeSpaghetti/tools/ATX_epigenomics-main/fastq2frags/Refseq/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa 

```
  
Also has index generated by Yeting 

Original file names: 	D01942_NG05827_200403_linker2_R2.fastq.gz (32GB) 
	                    D01942_NG05827_200403_S1_L001_R1_001.fastq.gz (47GB)

From https://github.com/atlasxomics/ATX_epigenomics/blob/2af49aa081c5846ccc9fe1b868d4982430feed5c/fastq2frags/README.md
read1: genomic sequence
read2: linker1 | barcodeA | linker2 | barcodeB | genomic sequence

Going to rename files since they don't match 
D01942_NG05827_200403_linker2_R2.fastq.gz     -> D01942_NG05827_200403_R2.fastq.gz 
D01942_NG05827_200403_S1_L001_R1_001.fastq.gz -> D01942_NG05827_200403_R1.fastq.gz 
  
  
## Trim fastq 

look at script /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/src/01_trim_fastq.sh
  
## Making sam file 

look at script /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/src/02_map_fastq.sh


## Making bam file 

```{bash}
# module load sambamba/0.6.7
cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/lowseq_alignment/
  
module load samtools
samtools view -bS -@ 8 -o D01942_NG05827_200403_aln.bam D01942_NG05827_200403_aln.sam

samtools sort -@ 8 -o D01942_NG05827_200403_aln_sort.bam D01942_NG05827_200403_aln.bam && samtools index -@ 8 D01942_NG05827_200403_aln_sort.bam || { echo "BAM sorting or indexing FAILED."; exit 1; }

samtools flagstat -@ 8 D01942_NG05827_200403_aln_sort.bam > "D01942_NG05827_200403_aln_sort_flagstat.txt" || { echo "samtools flagstat FAILED."; exit 1; }
```


This isn't working out well, I don't have the right barcode files, so abandoning this right now!

# 2025-11-28 

Jeff found the cram file for the alignment, so will try monopgen on that now!

It is stored here: /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment/	419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.cram

```{bash}
module load samtools
cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment

samtools view -@ 16 -b -T Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -o 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.cram
```

2025-11-30 
Bam file has been created! now let's move on to variant call 


Looks like file is already sorted, so we need to generate index for bam file
<!-- ```{bash}
module load sambamba 
sambamba index -t 8 --show-progress 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bai
``` -->

```{bash}
module load sambamba/0.6.7
module load python3/3.8.6
module load deeptools/3.5.1

cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment

sambamba index 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam

# create a bigwig file to check coverage! - using chunks of 1Mb
bamCoverage -p 4 -bs 1000000 -b 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam -o coverage.bw

```




# Script to download the phased vcf 

```{bash}
#!/bin/bash
#$ -P paxlab        # Set SCC project to charge
#$ -pe omp 8       # Request cores
#$ -l h_rt=12:00:00  # Specify hard time limit for the job
#$ -N download       # Name job
#$ -o /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs
#$ -e /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs
#$ -M preshita@bu.edu


# --- Configuration ---
MANIFEST_FILE="/projectnb/paxlab/presh/Data/variant_calling/phased_hg38_1000G_ref/phased-manifest_July2021.tsv"
# IMPORTANT: Replace this with the actual base URL where your files are hosted.
# Example: BASE_URL="https://example.com/data/"
BASE_URL="http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/" # <--- EDIT THIS LINE

# --- Script Start ---
echo "Starting download from manifest: $MANIFEST_FILE"
echo "Base URL: $BASE_URL"

# Check if wget or curl is available
if ! command -v wget &> /dev/null && ! command -v curl &> /dev/null; then
    echo "Error: Neither 'wget' nor 'curl' found. Please install one of them."
    exit 1
fi

# Loop through each line in the manifest file, extracting the filename
# We use 'awk' to get the first column (the filename)
while read -r line; do
    FILENAME=$(echo "$line" | awk '{print $1}')

    if [[ -z "$FILENAME" ]]; then # Skip empty lines
        continue
    fi

    FULL_URL="${BASE_URL}${FILENAME}"

    echo -e "\nDownloading: $FILENAME"
    echo "From: $FULL_URL"

    # --- Download the file ---
    # Use wget if available, otherwise fall back to curl
    if command -v wget &> /dev/null; then
        wget -c "$FULL_URL" # -c for continuing partial downloads
    elif command -v curl &> /dev_null; then
        curl -L -O "$FULL_URL" # -L to follow redirects, -O to use original filename
    fi

    if [[ $? -ne 0 ]]; then
        echo "ERROR: Download failed for $FILENAME."
    else
        echo "Download successful for $FILENAME."
    fi

done < "$MANIFEST_FILE"

echo -e "\nDownload process complete."
```


# Running monopogen on the deepseq bam file

Date: Mar 23 2026

We can run germline variant calling on each chr separately to increase the speed 

ref data is stored here: /projectnb/paxlab/presh/Data/variant_calling/phased_hg38_1000G_ref/


Creating monopgen env and installing monopogen again since I had to delete the previous one to free up space.
```{bash}
module load miniconda
conda create -n monopogen_env python=3.8 -y
conda activate monopogen_env
pip install -e /projectnb/paxlab/presh/software/Monopogen
```

```{bash}
path="/projectnb/paxlab/presh/software/Monopogen" # where Monopogen is downloaded
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps
python ${path}/src/Monopogen.py  preProcess --help
```


## Create a BAM file list
cat > /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq_bam_list.txt << 'EOF'
deepseq,/projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment/419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam
EOF

path="/projectnb/paxlab/presh/software/Monopogen"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps

## creating index file for bam file
module load samtools && cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment && samtools index -@ 8 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam


## preprocessing the bam file for monopogen

saved this in file: monopgen/preprocess.sh

```{bash}
#!/bin/bash -l

#$ -P paxlab            # Specify the SCC project name you want to use
#$ -l h_rt=24:00:00     # Specify the hard time limit for the job
#$ -N preprocess        # Give job a name
#$ -l mem_per_core=8G  # Request memory per core (adjust as needed)
#$ -pe omp 16           # Request 8 cores for parallel processing
#$ -o /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs  # Specify the path for standard output logs
#$ -e /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs  # Specify the path for error logs

path="/projectnb/paxlab/presh/software/Monopogen" # where Monopogen is downloaded
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps
python ${path}/src/Monopogen.py  preProcess --help

python ${path}/src/Monopogen.py preProcess \
  -b /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq_bam_list.txt \
  -o /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq \
  -a ${path}/apps -t 8

```

The preprocessing step splits the bam file into chr specific bam files.

I want to check mean coverage across each of the chr bam files to see if there are any issues with coverage before running the variant calling step.

```{bash}
cd /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq/Bam

module load samtools
echo -e "File\tMean_Coverage" > mean_coverage.txt
for f in *.bam; do
    echo "Processing $f"
    mean_cov=$(samtools depth "$f" | awk '{
        sum += $3; cnt++
    } END {
        if (cnt > 0) printf "%.6f\n", sum/cnt;
        else print "0"
    }')
    echo -e "${f}\t${mean_cov}" >> mean_coverage.txt
done

```


## script for running variant calling step of monopogen


```{bash}
#!/bin/bash -l
#$ -P paxlab
#$ -N monopogen_germline_deepseq
#$ -pe omp 16
#$ -l h_rt=48:00:00
#$ -l mem_per_core=8G
#$ -o /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs
#$ -e /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs

set -euo pipefail

# --- config ---
MONOPOGEN_PATH="/projectnb/paxlab/presh/software/Monopogen"
PREPROCESS_DIR="/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq"
OUT_DIR="/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq/germline"
REGION_LST="${MONOPOGEN_PATH}/resource/GRCh38.region.lst"
REF_FA="/projectnb/paxlab/presh/projects/spatial_atac/Data/hg38_resources/Homo_sapiens_assembly38.fasta"
THREADS="${NSLOTS:-16}"

# --- env ---
# module load miniconda
# conda activate monopogen_env
module load python3
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${MONOPOGEN_PATH}/apps"

mkdir -p "${OUT_DIR}"

# --- run ---
python "${MONOPOGEN_PATH}/src/Monopogen.py" germline \
  -a "${MONOPOGEN_PATH}/apps" \
  -t "${THREADS}" \
  -r "${REGION_LST}" \
  -p "${PREPROCESS_DIR}" \
  -g "${REF_FA}" \
  -s all \
  -o "${OUT_DIR}"

echo "Done: ${OUT_DIR}"

```







# redoing the lowseq cleaning 


Using this link for pre- processing - 
https://github.com/atlasxomics/ATX_epigenomics/tree/main/fastq2frags

```{bash}
cd /projectnb/paxlab/presh/software

git clone https://github.com/atlasxomics/ATX_epigenomics.git

cd ATX_epigenomics/fastq2frags/

# install chromap
curl -L https://github.com/haowenz/chromap/archive/refs/heads/li_dev4.zip -o li_dev4.zip
unzip li_dev4.zip
mv chromap-li_dev4 chromap
cd chromap && make
cd ..


# download reference 
wget https://latch-public.s3.amazonaws.com/test-data/13502/chromap_references/GRCh38.tar.gz
tar -xzvf GRCh38.tar.gz

curl -L https://sourceforge.net/projects/bbmap/files/BBMap_39.01.tar.gz/download -o BBMap_39.01.tar.gz 
tar -xvzf BBMap_39.01.tar.gz 

conda create -c conda-forge -c bioconda -c nodefaults -n snakemake snakemake

conda activate snakemake


/projectnb/paxlab/presh/software/ATX_epigenomics/fastq2frags/chromap/chromap \
      -t 8 \
      --preset atac \
      -x /projectnb/paxlab/presh/software/ATX_epigenomics/fastq2frags/hg38/GRCh38/GRCh38_genome.index \
      -r /projectnb/paxlab/presh/software/ATX_epigenomics/fastq2frags/hg38/GRCh38/GRCh38_genome.fa \
      -1 /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/preprocessing/fastq/D01942_NG05827_200403_R1.fastq.gz  \
      -2 /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/preprocessing/fastq/D01942_NG05827_200403_R2.fastq.gz \
      --SAM  -o /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/lowseq_output.sam \
      -b /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/preprocessing/fastq/D01942_NG05827_200403_R2.fastq.gz \
      --read-format bc:22:29,bc:60:67,r1:0:-1,r2:117:-1 \
        > /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/chromap_run.log 2>&1

```


```{bash}

# -t sets threads, -o specifies output, -n sorts by name (optional, default is coordinate)

module load sambamba/0.6.7

cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/
sambamba view -S -t 8 -p -f bam /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/lowseq_output.sam | sambamba sort -p -t 8 -o lowseq.sorted.bam /dev/stdin


# sambamba index -t 4 lowseq.sorted.bam
```


# running monopogen on the lowseq bam file

cat > /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq_bam_list.txt << 'EOF'
lowseq,/projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827_lowseq/lowseq.sorted.bam
EOF


```{bash}
cd /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq/Bam

module load samtools
echo -e "File\tMean_Coverage" > mean_coverage.txt
for f in *.bam; do
    echo "Processing $f"
    mean_cov=$(samtools depth "$f" | awk '{
        sum += $3; cnt++
    } END {
        if (cnt > 0) printf "%.6f\n", sum/cnt;
        else print "0"
    }')
    echo -e "${f}\t${mean_cov}" >> mean_coverage.txt
done

```


variant calling script for lowseq data
```{bash}

#!/bin/bash -l
#$ -P paxlab
#$ -N monopogen_germline_deepseq
#$ -pe omp 16
#$ -l h_rt=48:00:00
#$ -l mem_per_core=8G
#$ -o /projectnb/paxlab/presh/projects/spatial_atac/analysis/qsub_logs/germline_deepseq
#$ -e /projectnb/paxlab/presh/projects/spatial_atac/analysis/qsub_logs/germline_deepseq_error

set -euo pipefail

# --- config ---
MONOPOGEN_PATH="/projectnb/paxlab/presh/software/Monopogen"

OUT_DIR="/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq"
REF_FA="/projectnb/paxlab/presh/projects/spatial_atac/Data/hg38_resources/Homo_sapiens_assembly38.fasta"

REGION_LST="${MONOPOGEN_PATH}/resource/GRCh38.region.lst"
# Use your canonical region list if preferred
# REGION_LST="/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/GRCh38.chr1_22_X_Y.region.lst"
WORK_DIR="/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq"
REF_FA="/projectnb/paxlab/presh/projects/spatial_atac/Data/hg38_resources/Homo_sapiens_assembly38.fasta"
IMPUTATION_PANEL="/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/phased_hg38_1000G_ref/"
STEP="all"
THREADS="${NSLOTS:-16}"

# --- env ---
module load python3
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${MONOPOGEN_PATH}/apps"

mkdir -p "${OUT_DIR}"
cd "${WORK_DIR}"

# --- run ---
python "${MONOPOGEN_PATH}/src/Monopogen.py" germline \
  -r "${REGION_LST}" \
  -s "${STEP}" \
  -o "${OUT_DIR}" \
  -g "${REF_FA}" \
  -p "${IMPUTATION_PANEL}" \
  -a "${MONOPOGEN_PATH}/apps" \
  -t "${THREADS}"  --norun TRUE

echo "Done: ${OUT_DIR}"

```


adding modules needed to the script -> 

cd Script
for f in runGermline_*.sh; do
  {
    echo "#!/bin/bash -l"
    echo "#$ -P paxlab"
    echo "#$ -pe omp 4"
    echo "#$ -l h_rt=24:00:00"
    echo "#$ -l mem_per_core=8G"
    echo "source ~/.bashrc"
    echo "module load samtools/1.12"
    echo "module load htslib/1.21"
    sed 's|/projectnb/paxlab/presh/software/Monopogen/apps/bcftools|/projectnb/paxlab/presh/software/bcftools_1.8/bcftools|g; s| /projectnb/paxlab/presh/software/Monopogen/apps/bgzip|bgzip|g' "$f"
  } > "${f}.tmp" && mv "${f}.tmp" "$f" && chmod +x "$f"
done

# to test one script
cd /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq/Script
qsub -V -N runGermline_chr17_1-50000001 'runGermline_chr17:1-50000001.sh'
qstat -u preshita 

# to run all
for f in runGermline_*.sh; do
  # Extract job name from filename (remove .sh and use as job ID)
  job_name=${f%.sh}
  job_name=${job_name//:/_}  # Replace colons with underscores
  qsub -V -N "$job_name" "$f"
done



# going back to lowseq and do somatic snv calling 

so this is done using LD refinement
Needs a cell barcode file file with 2 cols, cell barcode, number of reads for that cell. 

Use ArchR for this 



```{R}
.libPaths('/projectnb/paxlab/presh/env/R_4.5.2/ArchR_libs')
.libPaths()
library(ArchR)
library(parallel)
set.seed(1)
# addArchRLocking(locking = F)
addArchRGenome("hg38")


addArchRThreads(threads = 16) 

arrow.path = '/projectnb/paxlab/yeting/SpatialATACseq/results/preprocessed/D01942_filtered_ArchR_Output/ArrowFiles'
deep_ArrowFiles = c(file.path(arrow.path, 'Deepseq.arrow'))
deepseq.proj <- ArchRProject(
  ArrowFiles = deep_ArrowFiles, 
  outputDirectory = "/projectnb/paxlab/presh/Data",
  copyArrows = F
)

df = as.data.frame(deepseq.proj@cellColData)
result <- data.frame(cell = gsub("Deepseq#", "", rownames(df)), id = df$nFrags)
result$cell <- gsub("-1", "", result$cell)
head(result)

write.csv(result, file = "/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/deepseq_cell_data.csv", row.names = FALSE)


low_ArrowFiles = c(file.path(arrow.path, 'Lowseq.arrow'))
lowseq.proj <- ArchRProject(
  ArrowFiles = low_ArrowFiles, 
  outputDirectory = "/projectnb/paxlab/presh/Data",
  copyArrows = F
)

df = as.data.frame(lowseq.proj@cellColData)
result <- data.frame(cell = gsub("Lowseq#", "", rownames(df)), id = df$nFrags)
result$cell <- gsub("-1", "", result$cell)
head(result)

write.csv(result, file = "/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq_cell_data.csv", row.names = FALSE)

```


then there are 3 steps needed - 



I need to merge chunks first -> 

```{bash}
#!/bin/bash
# merge_chr_chunks.sh -- merge all per-chunk chrN:*-*.gl.vcf.gz into 1 per chrN.gl.vcf.gz


module load htslib/1.16
module load bcftools/1.16


for CHR in {1..22}; do
    # Find all chunked files for this chromosome, sorted in natural order
    FILES=$(ls chr${CHR}:*.gl.vcf.gz 2>/dev/null | sort -V)
    
    if [[ -z "$FILES" ]]; then
        echo "No files found for chr${CHR}, skipping."
        continue
    fi
    
    echo "Merging for chr${CHR}:"
    echo "$FILES"
    
    # Concatenate using bcftools
    bcftools concat -Oz $FILES -o chr${CHR}.gl.vcf.gz
    
    # Index the merged VCF
    tabix -p vcf chr${CHR}.gl.vcf.gz
done
```

merging the phased vcf gz

```{bash}
#!/bin/bash
# simple_merge.sh

for CHR in {1..22}; do
    CHUNKS=$(ls chr${CHR}:*phased.vcf.gz 2>/dev/null | sort -V)
    
    if [[ -z "$CHUNKS" ]]; then
        echo "Skipping chr${CHR}: no chunks found."
        continue
    fi
    
    OUTPUT="chr${CHR}.phased.vcf.gz"
    echo "Merging chr${CHR}..."
    
    # Use --naive-force to ignore header mismatches
    bcftools concat -Oz --naive-force $CHUNKS -o "$OUTPUT"
    tabix -p vcf "$OUTPUT"
    
    echo "Done: $OUTPUT"
done

```


# variant calling with LD refinement

MONOPOGEN_PATH="/projectnb/paxlab/presh/software/Monopogen"
REGION_LST="${MONOPOGEN_PATH}/resource/GRCh38.region.lst"
REF_FA="/projectnb/paxlab/presh/projects/spatial_atac/Data/hg38_resources/Homo_sapiens_assembly38.fasta"

python  "${MONOPOGEN_PATH}/src/Monopogen.py"  somatic  \
    -a   "${MONOPOGEN_PATH}/apps" -r /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/chr_region.lst   -t 22 \
    -i  "/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq"  -l  /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq_cell_data.csv   -s featureInfo     \
    -g   "${REF_FA}"



python  "${MONOPOGEN_PATH}/src/Monopogen.py"  somatic  \
    -a  "${MONOPOGEN_PATH}/apps"  -r /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/chr_region.lst   -t 8 \
    -i  "/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq"  -l  /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq_cell_data.csv   -s cellScan     \
    -g   "${REF_FA}"


python  "${MONOPOGEN_PATH}/src/Monopogen.py"  somatic  \
-a  "${MONOPOGEN_PATH}/apps"  -r /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/chr_region.lst   -t 22 \
-i  "/projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq"  -l  /projectnb/paxlab/presh/projects/spatial_atac/Data/variant_calling/lowseq_cell_data.csv   -s LDrefinement     \
-g   "${REF_FA}"