#!/bin/bash -l
#$ -P paxlab
#$ -N calicost_lowseq_489_run3
#$ -wd /projectnb/paxlab/presh/projects/spatial_atac
#$ -pe omp 8
#$ -l mem_per_core=8G
#$ -l h_rt=12:00:00
#$ -j y
#$ -o /projectnb/paxlab/presh/projects/spatial_atac/analysis/qsub_logs/calicost_lowseq_489_run3_$JOB_ID.log
#$ -m bea
#$ -M preshita@bu.edu

set -euo pipefail

TISSUE="lowseq_489"
RUN="run3"
PROJECT_ROOT="/projectnb/paxlab/presh/projects/spatial_atac"
CALICOST_SRC_DIR="${PROJECT_ROOT}/analysis/src/cnv_calling/calicoST"
OUTPUT_ROOT="${PROJECT_ROOT}/Data/04_analysis/cnv/calicoST/${TISSUE}/${RUN}"
PARSED_INPUTS_DIR="${OUTPUT_ROOT}/parsed_inputs"
PYTHON="/projectnb/paxlab/presh/env/calicost_env/bin/python3"
NORMAL_BARCODES="${PROJECT_ROOT}/analysis/binsize_comparison/normal_barcodes/${TISSUE}_normal_barcodes.csv"

echo "=== CalicoST pipeline: ${TISSUE} ${RUN} (k=5 spot aggregation) ==="
echo "Job ID: ${JOB_ID}"
echo "Start: $(date)"
echo "Host: $(hostname)"

${PYTHON} -c "import sys; sys.path.insert(0,'/projectnb/paxlab/presh/software/CalicoST/src'); import calicost; print('CalicoST loaded from', calicost.__file__)"

if [ ! -f "${NORMAL_BARCODES}" ]; then
    echo "ERROR: Normal barcodes file not found: ${NORMAL_BARCODES}"
    exit 1
fi
echo "Original normal barcodes: $(wc -l < ${NORMAL_BARCODES}) spots"

cd "${CALICOST_SRC_DIR}"

# ============================================================
# Step 2: Build parsed_inputs with k=5 spatial aggregation
# (Uses existing intermediate/ files from run1; reuses the same
#  ArchR exports — no need to re-run 1_export_archr_data.R)
# ============================================================
echo ""
echo "--- Step 2: Building k=5 aggregated parsed_inputs ---"
echo "Start: $(date)"

mkdir -p "${PARSED_INPUTS_DIR}"

${PYTHON} 2_build_calicost_inputs.py "${TISSUE}" \
    --snps-per-bin 200 \
    --aggregate-k 5 \
    --normalidx-file "${NORMAL_BARCODES}" \
    --output-dir "${PARSED_INPUTS_DIR}"

# Verify super-spot normal barcodes were generated
SUPERSPOT_NORMALS="${PARSED_INPUTS_DIR}/superspot_normal_barcodes.csv"
if [ ! -f "${SUPERSPOT_NORMALS}" ]; then
    echo "ERROR: superspot_normal_barcodes.csv not generated by step 2"
    exit 1
fi
echo "Super-spot normal barcodes: $(wc -l < ${SUPERSPOT_NORMALS}) super-spots"

echo "Step 2 complete: $(date)"

# Symlink parsed_inputs into purity/ and cna/
mkdir -p "${OUTPUT_ROOT}/purity" "${OUTPUT_ROOT}/cna"

if [ ! -e "${OUTPUT_ROOT}/purity/parsed_inputs" ]; then
    ln -s "${PARSED_INPUTS_DIR}" "${OUTPUT_ROOT}/purity/parsed_inputs"
    echo "Symlinked parsed_inputs → run3/purity/"
fi

if [ ! -e "${OUTPUT_ROOT}/cna/parsed_inputs" ]; then
    ln -s "${PARSED_INPUTS_DIR}" "${OUTPUT_ROOT}/cna/parsed_inputs"
    echo "Symlinked parsed_inputs → run3/cna/"
fi

# ============================================================
# Step 3: Tumor purity estimation
# ============================================================
echo ""
echo "--- Step 3: Tumor purity estimation (run3, k=5 super-spots) ---"
echo "Start: $(date)"

${PYTHON} 3_run_purity.py tissue/${TISSUE}_run3/config_purity.yaml

echo "Step 3 complete: $(date)"

# ============================================================
# Step 4: CNA + clone calling
# ============================================================
echo ""
echo "--- Step 4: CNA + clone calling ---"
echo "Start: $(date)"

${PYTHON} 4_run_cna.py tissue/${TISSUE}_run3/config_cna.yaml

echo "Step 4 complete: $(date)"

# ============================================================
# Step 5: Postprocessing and visualization
# ============================================================
echo ""
echo "--- Step 5: Postprocessing and visualization ---"
echo "Start: $(date)"

${PYTHON} 5_postprocess_visualize.py "${TISSUE}" --n-clones 3 --n-clones-purity 5 \
    --output-base "${OUTPUT_ROOT}"

echo "Step 5 complete: $(date)"

echo ""
echo "=== CalicoST pipeline complete: ${TISSUE} ${RUN} ==="
echo "End: $(date)"
echo "Results: ${OUTPUT_ROOT}"
