---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# Creating Xenium object 

```{r}
.libPaths('/projectnb/paxlab/presh/giotto_libs')
.libPaths()

library(Giotto)
# library(ggplot2)

# Ensure Giotto can access the python env
set_giotto_python_path(python_path = '/usr3/graduate/preshita/.conda/envs/giotto_env/bin/python', verbose = NULL, initialize = TRUE)


data_path = '/projectnb/paxlab/DATA/DriesSpatial/Xenium/output-XETG00253__0048833__488B__20241217__182301'


results_folder <- '/projectnb/paxlab/presh/giotto_output'

instrs <- createGiottoInstructions(
  show_plot = T,
  return_plot = FALSE,
  save_plot = FALSE,
  save_dir = results_folder
)

data_path <- '/projectnb/paxlab/DATA/DriesSpatial/Xenium/output-XETG00253__0048833__488B__20241217__182301'
x <- importXenium(data_path)
force(x)

xenium488B  <- giotto(instructions = instrs) |>
  setGiotto(x$load_polys()) |>
  setGiotto(x$load_expression('/projectnb/paxlab/DATA/DriesSpatial/Xenium/output-XETG00253__0048833__488B__20241217__182301/cell_feature_matrix/')) |>
  setGiotto(x$load_cellmeta()) |>
  addSpatialCentroidLocations()

force(xenium488B)

plot(xenium488B@spatial_locs$cell$raw)


xenium488B = filterGiotto(xenium488B, feat_det_in_min_cells = 100, 
                  min_det_feats_per_cell = 20, 
                  expression_threshold = 1)

norm_name <- 'normalized'
xenium488B = normalizeGiotto(xenium488B)

```

## Statistics
```{r}

xenium488B = addStatistics(xenium488B)

xenium_crop <- subsetGiottoLocs(xenium488B, x_min = 5000, x_max = 10600)
my_spatPlot <- spatPlot2D(gobject = xenium_crop,
                          spat_unit = 'cell',
                          cell_color = 'leiden_clus',
                          point_size = 0.025,
                          point_shape = 'no_border',
                          # color_as_factor = F,
                          show_legend = TRUE,point_border_stroke = 0,
                          background_color = 'black', show_plot = T,
                          save_param = list(
                            save_name = 'sg_spat_leiden',
                            base_width = 15,
                            base_height = 15))




```

## PCA + UMAP 
```{r}

xenium_crop = runPCA(gobject = xenium_crop,
            spat_unit = 'cell',
            expression_values = norm_name)

screePlot(xenium_crop)

# Run and Plot tSNE and UMAP
xenium_crop = runUMAP(xenium_crop,
             expression_values = norm_name,
             dimensions_to_use = 1:13,
             spat_unit = 'cell')

plotUMAP(xenium_crop,
         point_size = 0.01,
         save_param = list(
           save_name = 'sg_UMAP'))

# Clustering and UMAP cluster visualization
xenium_crop = createNearestNetwork(xenium_crop,
                          dimensions_to_use = 1:13,
                          expression_values = norm_name,
                          k = 25,
                          spat_unit = 'cell')
xenium_crop = doLeidenCluster(xenium_crop,
                     resolution = 0.1,
                     n_iterations = 10,
                     spat_unit = 'cell')

# Plot Leiden clusters onto UMAP
plotUMAP(gobject = xenium_crop,
         spat_unit = 'cell',
         # select_cells = healthy_cancer,
         cell_color = 'leiden_clus',
         show_legend = TRUE,
         point_size = 0.01,
         point_shape = 'no_border',
         save_param = list(save_name = 'sg_umap_leiden'))




```



# Creating ATACseq giotto obj 

```{r}

# Testing clustering with the spatial ATACseq dataset #########################
test2 = readRDS('/Users/preshitadave/Downloads/saveAtacgiotto.rds')

sg <- test2$Deepseq


# we should filter out more cells since we know that the borders are not great 
int.cells.atac = read.csv('/Users/preshitadave/Downloads/int_cells_trim_atac.csv', header = T, row.names = 1)
int.cells.atac =int.cells.atac$x

sg2 = subsetGiotto(
  sg,
  spat_unit = ":all:", feat_type = ":all:", 
  cell_ids = int.cells.atac
)



sg2 = filterGiotto(sg2, feat_det_in_min_cells = 100,
                  spat_unit = 'cell',
                  feat_type = 'atac',
                  expression_values = 'GeneScoreMatrix',
                  min_det_feats_per_cell = 20, 
                  expression_threshold = 1)


norm_name <- 'normalized'
activeSpatUnit(sg2) <- 'cell'
activeFeatType(sg2) <- 'atac'
sg2 = normalizeGiotto(sg2, norm_methods = 'standard', name = norm_name, expression_values = 'GeneScoreMatrix')
# Statistics
sg2 = addStatistics(sg2, expression_values = norm_name)


test <- spatPlot2D(gobject = sg2,
                   show_image = F,
                   point_alpha = 0.7,
                   point_size = 0.6,
                   background_color = 'black',
                   cell_color = 'nr_feats',
                   color_as_factor = F,
                   save_param = list(
                     save_name = 'nr_feats',
                     base_width = 15,
                     base_height = 15))

sg2 <- calculateHVF(gobject = sg2, )

sg2 = runPCA(gobject = sg2,
            spat_unit = 'cell',
            expression_values = norm_name)

screePlot(sg2)

# Run and Plot tSNE and UMAP
sg2 = runUMAP(sg2,
             expression_values = norm_name,
             dimensions_to_use = 1:13,
             spat_unit = 'cell')

plotUMAP(sg2,
         point_size = 0.01,
         save_param = list(
           save_name = 'sg_UMAP'))

# Clustering and UMAP cluster visualization
sg2 = createNearestNetwork(sg2,
                          dimensions_to_use = 1:13,
                          expression_values = norm_name,
                          k = 25,
                          spat_unit = 'cell')
sg2 = doLeidenClusterIgraph(sg2,
                     resolution = 0.4,
                     n_iterations = 10,
                     spat_unit = 'cell')

# Plot Leiden clusters onto UMAP
plotUMAP(gobject = sg2,
         spat_unit = 'cell',
         # select_cells = healthy_cancer,
         cell_color = 'leiden_clus',
         show_legend = TRUE,
         point_size = 0.01,
         point_shape = 'no_border',
         save_param = list(save_name = 'sg_umap_leiden'))

my_spatPlot <- spatPlot2D(gobject = sg2,
                          spat_unit = 'cell',
                          cell_color = 'leiden_clus',
                          point_size = 0.025,
                          point_shape = 'no_border',
                          # color_as_factor = F,
                          show_legend = TRUE,point_border_stroke = 0,
                          background_color = 'black',
                          save_param = list(
                            save_name = 'sg_spat_leiden',
                            base_width = 15,
                            base_height = 15))
```


# Align using Giotto's alignment tool
```{r}
atac_align <- spatPlot2D(gobject = sg2,
                          spat_unit = 'cell',
                          cell_color = 'leiden_clus',
                          point_size = 0.025,
                          point_shape = 'no_border',
                          # color_as_factor = F,
                          show_legend = TRUE,point_border_stroke = 0,
                          background_color = 'black',
                         return_plot = T,
                          save_param = list(
                            save_name = 'sg_spat_leiden',
                            base_width = 15,
                            base_height = 15))

xen_align <- spatPlot2D(gobject = xenium488B,
                         spat_unit = 'cell',
                         cell_color = 'leiden_clus',
                         point_size = 0.025,
                         point_shape = 'no_border',
                         # color_as_factor = F,
                         show_legend = TRUE,
                        point_border_stroke = 0,
                         background_color = 'black',
                        show_plot = T,
                        return_plot = T,
                         save_param = list(
                           save_name = 'sg_spat_leiden',
                           base_width = 15,
                           base_height = 15))

points <- interactiveLandmarkSelection(xen_align, atac_align)
force(points)

# > points
# [[1]]
#            x          y
# 1   5990.106 -1935.6520
# 2   6522.827 -2184.6869
# 3   6640.441 -2120.6494
# 4   6931.016 -2376.7996
# 5  10203.409 -1211.8988
# 6  10322.300 -2346.0708
# 7  10414.771 -2169.8887
# 8  10487.427 -2390.1163
# 9   9747.658 -1085.2680
# 10  6438.514  -859.5347
# 11  7620.823 -1145.8305
# 12  8334.172 -1206.3931
# 13  8704.056 -1134.8192
# 14  5474.172  -991.6713
# 15  6009.184 -1035.7168
# 16  5262.810 -1938.6498
# 
# [[2]]
#            x        y
# 1  1532.0432 5940.063
# 2  2230.2891 5614.557
# 3  2368.3145 5636.750
# 4  2774.2714 5340.835
# 5  6961.6426 7271.680
# 6  7222.5319 5769.912
# 7  7401.0351 5984.450
# 8  7455.9592 5732.923
# 9  6432.9985 7367.853
# 10 2059.6701 7523.208
# 11 3515.1578 7057.142
# 12 4496.9254 7064.540
# 13 4998.1074 7212.497
# 14  810.1477 7397.444
# 15 1510.4295 7316.068
# 16  542.3929 5962.257

affine_mtx <- calculateAffineMatrixFromLandmarks(
  source = points[[2]], # from slice 2
  target = points[[1]] # from slice 1
)

# > affine_mtx
#             x          y          
# x  0.75980146 0.03701443  4618.899
# y -0.03802109 0.70688574 -6088.528
#    0.00000000 0.00000000     1.000

force(affine_mtx)

sg_affine <- affine(sg2, y = affine_mtx, pre_multiply = T)

# Plot the first layer
terra::plot(xenium488B@spatial_info$cell)

# Add the second layer with terra-specific parameters
terra::points(sg_affine@spatial_locs$cell$raw@coordinates, 
            col = "red",   cex = 0.3)        
```


# Differential gene expression 

## Gini markers 

```{r}
gini_markers <- findMarkers_one_vs_all(gobject = xenium488B,
                                       method = "gini",
                                       expression_values = "normalized",
                                       cluster_column = "leiden_clus",
                                       min_feats = 10)

topgenes_gini <- gini_markers[, head(.SD, 5), by = "cluster"]$feats
```


```{r}
gini_markers2 = gini_markers[gini_markers$feats %in% topgenes_gini, ]

plotMetaDataHeatmap(xenium488B, 
                    selected_feats = unique(topgenes_gini),
                    metadata_cols = "leiden_clus",
                    x_text_size = 10, y_text_size = 10)
```

```{r}
dimFeatPlot2D(xenium488B, 
              expression_values = "scaled",
              feats = (unique(topgenes_gini)),
              cow_n_col = 5, 
              point_size = 1,
              save_param = list(base_width = 15, base_height = 20))

```

## scran markers

```{r}
scran_markers <- findMarkers_one_vs_all(gobject = xenium488B,
                                       method = "scran",
                                       expression_values = "normalized",
                                       cluster_column = "leiden_clus",
                                       min_feats = 10)

topgenes_scran <- scran_markers[, head(.SD, 5), by = "cluster"]$feats
```


```{r}
plotMetaDataHeatmap(xenium488B, 
                    selected_feats = unique(topgenes_scran),
                    metadata_cols = "leiden_clus",
                    x_text_size = 10, y_text_size = 10)
```

```{r}
dimFeatPlot2D(xenium488B, 
              expression_values = "scaled",
              feats = sort(unique(topgenes_scran)),
              cow_n_col = 5, 
              point_size = 1,
              save_param = list(base_width = 20, base_height = 20))
```

# Gene set co-regulation analysis

Have to run this in R 4.5!!!!
fgsea will not run otherwise 

Date: 2025-12-02

Ref: https://bioconductor.org/packages/release/bioc/vignettes/fgsea/inst/doc/geseca-tutorial.html

```{r}
library(fgsea)
library(msigdbr)
set.seed(1)
library(Seurat)
library(SeuratObject) 

seurat_object <- giottoToSeuratV5(gobject = xenium_crop, tech = 'Xenium')
seurat_object <- ScaleData(seurat_object)

E <- seurat_object@reductions[["pca"]]@feature.loadings[,1:30]

gsets <- msigdbr(species="human", category="H")
gsets <- split(gsets$gene_symbol, gsets$gs_name)

set.seed(1)
gesecaRes <- geseca(gsets, E, minSize = 15, maxSize = 500, center = FALSE, eps = 1e-100)

head(gesecaRes, 10)
```

```{r}
topPathways <- gesecaRes[, pathway] |> head(6)
titles <- sub("HALLMARK_", "", topPathways)
pvals <- gesecaRes[match(topPathways, pathway), pval]
pvals <- paste("p-value:", formatC(pvals, digits = 1, format = "e"))

titles <- paste(titles, pvals, sep = "\n")

plots <- fgsea::plotCoregulationProfileReduction(
    gsets[topPathways], seurat_object, assay = 'rna',
    reduction = "umap", title = titles,
    raster = TRUE, raster.dpi = c(500, 500),
    pt.size = 2.5
)


plots <- lapply(plots, function(p){
    p + theme(plot.title = element_text(hjust=0), text = element_text(size=10))
})


cowplot::plot_grid(plotlist = plots, ncol = 2)

```

```{r}
if (packageVersion("Seurat") >= "5.1.0"){
    sfactors <- ScaleFactors(seurat_object@images$slice1)
    pt.size.factor <- 1.5 * sfactors$fiducial / sfactors$hires
}

pt.size.factor <- 1.6

ps <- plotCoregulationProfileSpatial(gsets[topPathways], seurat_object,
                                     title=titles)

cowplot::plot_grid(plotlist=ps, ncol=2)
```

```{r}
library(Seurat)
packageVersion('Seurat')
library(arrow, lib.loc = '/projectnb/paxlab/presh/giotto_libs')



path <- "/projectnb/paxlab/DATA/DriesSpatial/Xenium/output-XETG00253__0048833__488B__20241217__182301"
# Load the Xenium data
seurat_object <- giottoToSeuratV5(gobject = xenium_crop, tech = 'Xenium')

# Normalize and scale data
xobj <- NormalizeData(seurat_object, normalization.method = "LogNormalize", scale.factor = 1000, verbose = FALSE)
xobj <- FindVariableFeatures(xobj, nfeatures = 2000, verbose = FALSE)
xobj <- ScaleData(xobj, verbose = FALSE)

# Perform PCA and UMAP dimensionality reduction
xobj <- RunPCA(xobj, verbose = FALSE)
xobj <- RunUMAP(xobj, dims = 1:20)

# xobj@reductions$pca <- NULL
# xobj@assays$Xenium@layers$scale.data <- NULL
# xobj@assays$Xenium@layers$data <- NULL
seurat_object$x = seurat_object$sdimx
seurat_object$y = seurat_object$sdimy

# xobj <- Load10X_Spatial(data.dir = path , filename = "filtered_feature_bc_matrix.h5")



ImageDimPlot(seurat_object,  dark.background = FALSE, size = 0.5, 
                   flip_xy = TRUE) + 
    theme(legend.position = "none")


```

Trial data in tutorial 
```{r}
trial_xobj <- readRDS(url("https://alserglab.wustl.edu/files/fgsea/xenium-human-ovarian-cancer.rds"))
```



## try to create seurat xenium obj 

```{r}
library(Seurat)
packageVersion('Seurat')

path <- "/projectnb/paxlab/DATA/DriesSpatial/Xenium/output-XETG00253__0048833__488B__20241217__182301"
library(arrow, lib.loc = '/projectnb/paxlab/presh/giotto_libs')

xobj.seu = LoadXenium(
  path,
  fov = "fov",
  assay = "Xenium",
  mols.qv.threshold = 20,
  cell.centroids = TRUE,
  molecule.coordinates = TRUE,
  segmentations = NULL,
  flip.xy = FALSE
)

# xobj.seu.2 = ReadXenium(
#   path,
#   outs = c("segmentation_method", "matrix", "microns"),
#   type = "centroids",
#   mols.qv.threshold = 20,
#   flip.xy = F
# )

coords <- data.table::as.data.table(xobj.seu@images$fov@boundaries$centroids@coords)
xobj.seu@meta.data <- cbind(xobj.seu@meta.data, coords)

xobj.seu <- subset(xobj.seu, subset = nCount_Xenium > 50)
xobj.seu.crop <- xobj.seu[, xobj.seu$x > 5000 & xobj.seu$x < 10600]

# Normalize and scale data
xobj.seu.crop <- NormalizeData(xobj.seu.crop, normalization.method = "LogNormalize", scale.factor = 1000, verbose = FALSE)
xobj.seu.crop <- FindVariableFeatures(xobj.seu.crop, nfeatures = 2000, verbose = FALSE)
xobj.seu.crop <- ScaleData(xobj.seu.crop, verbose = FALSE)

# Perform PCA and UMAP dimensionality reduction
xobj.seu.crop <- RunPCA(xobj.seu.crop, verbose = FALSE)
xobj.seu.crop <- RunUMAP(xobj.seu.crop, dims = 1:20)
xobj.seu.crop <- FindNeighbors(xobj.seu.crop, reduction = "pca", dims = 1:30)
xobj.seu.crop <- FindClusters(xobj.seu.crop, resolution = 0.2)

# xobj.seu.crop@reductions$pca <- NULL
# xobj.seu.crop@assays$Xenium@layers$scale.data <- NULL
# xobj.seu.crop@assays$Xenium@layers$data <- NULL


ImageDimPlot(xobj.seu.crop, 
                   dark.background = T, size = 0.5, 
                   flip_xy = F)  + ggplot2::coord_flip() + ggplot2::scale_x_reverse()


DimPlot(xobj.seu.crop,  raster = FALSE, pt.size = 0.5, stroke.size = 0.0) + 
     ggplot2::coord_fixed()

```

Let's fix resolution 0.2 




```{r}
library(fgsea)
library(msigdbr)
set.seed(1)
xobj.seu.crop <- RunPCA(xobj.seu.crop, verbose = F, rev.pca = TRUE, reduction.name = "pca.rev", 
               reduction.key="PCR_", npcs=30)

E <- xobj.seu.crop@reductions$pca.rev@feature.loadings

gsets <- msigdbr(species="human", category="H")
gsets <- split(gsets$gene_symbol, gsets$gs_name)


gesecaRes <- geseca(gsets, E, minSize = 15, maxSize = 500, center = FALSE, eps = 1e-100)

head(gesecaRes, 10)

topPathways <- gesecaRes[, pathway] |> head(4)
titles <- sub("HALLMARK_", "", topPathways)
```



```{r}
topPathways <- gesecaRes[, pathway][9:12]
titles <- sub("HALLMARK_", "", topPathways)

plots <- fgsea::plotCoregulationProfileReduction(
    gsets[topPathways], xobj.seu.crop, 
    reduction = "umap", title = titles,
    raster = TRUE, raster.dpi = c(500, 500),
    pt.size = 2.5
)

plots <- lapply(plots, function(p){
    p + ggplot2::theme(plot.title = element_text(hjust=0), text = element_text(size=8))
})


cowplot::plot_grid(plotlist = plots, ncol = 2)
```


```{r}


imagePlots <- plotCoregulationProfileImage(
    gsets[topPathways], object = xobj.seu.crop, 
    dark.background = FALSE, 
    title = titles, 
    size=0.8
)

imagePlots <- lapply(imagePlots, function(p){
    suppressMessages(
        p + ggplot2::coord_flip() + ggplot2::scale_x_reverse() 
    )
})

cowplot::plot_grid(plotlist = imagePlots, ncol = 2)


```

## Marker analysis 
```{r}
xenium.markers <- FindAllMarkers(xobj.seu.crop, only.pos = TRUE)

library(dplyr)

sel.markers = xenium.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1 & pct.1 > 0.6 & pct.2 < 0.4)

FeaturePlot(xobj.seu.crop, features = c("MS4A1", "TIGIT", "CD3E", "EPCAM", "CLEC14A", "FCGR3A", "LILRB4", "WNT2",
    "CD8A"))


FeaturePlot(xobj.seu.crop, features = c("ESR1", "ERBB2", "PGR"))
```


## barplot 
















