---
title: "7_variant_calling_atac"
---

Going to utilize Monopogen for variant call 

# Install Monopogen

Creating a conda env 
```{bash}
cd /projectnb/paxlab/presh

module load miniconda 

conda create -n monopogen_env python=3.8

git clone https://github.com/KChen-lab/Monopogen.git
cd Monopogen

conda activate monopogen_env
pip install -e .


```

I get this warning: 
DEPRECATION: Legacy editable install of Monopogen==1.0.0 from file:///projectnb/paxlab/presh/Monopogen (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  
But looks like it installed so I will move ahead for now. 
  
  
Other packages to load -    
  
!Note We have put the binary compatibility tools including samtools, bcftools, beagle in the app folder. We fixed the version because the output formats vary a lot with different versions. If you are not able to run them, you can compile them in you system. We only test on these tools on following versions:
  
What they recommend - 
samtools Version: 1.2 (using htslib 1.2.1)
bcftools Version: 1.8 (using htslib 1.8)
beagle.27Jul16.86a.jar (version 4.1)
tabix Version: 1.9
bgzip Version: 1.9

  
  
bcftools: error while loading shared libraries: libbz2.so.1.0: not able to open shared object file: No such file or directly
Adding the apps folder of Monopogen in your library environment

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/projectnb/paxlab/presh/Monopogen/apps

AssertionError: Program vcftools cannot be found!
You may set the read/write permission on the folder xx/apps as

chmod 770 -R  /xx/apps
  
```{bash }

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/projectnb/paxlab/presh/Monopogen/apps
```

  
  
```{bash}
path="/projectnb/paxlab/presh/Monopogen"  # where Monopogen is downloaded
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${path}/apps
python ${path}/src/Monopogen.py  preProcess --help
```



First I need to convert bed to bam file to run the tool!
```{r}
cd /projectnb/paxlab/presh/Data/hg38_resources

https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta
https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta.fai
```


```{bash}
module load bedtools
bedToBam -i input.bed -g genome.txt > output.bam

cd /projectnb/paxlab/presh/Data/variant_calling
bedtools bedtobam -i /projectnb/paxlab/presh/Data/deepseq.fragments.sort.filtered.bed -g /projectnb/paxlab/presh/Data/hg38_resources/Homo_sapiens_assembly38.fasta
```



This doesn't work, we can't work our way back from fragments file to bam file!!!!

Need bam or fastq file 


# Lowseq fastq files

Date: Nov 10 2025 

Starting with trimming lowseq fastq files and aligning them to get bam!

using this as reference: https://github.com/atlasxomics/ATX_epigenomics/tree/2af49aa081c5846ccc9fe1b868d4982430feed5c/fastq2frags

And Yeting's scripts as reference located here: /projectnb/paxlab/Projects/CodeSpaghetti/src/00_fastq2frags


## Finding  hg38 ref 
```{bash}
cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/
conda create --prefix /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/chromap_env  python=3.9
conda activate /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/chromap_env      
conda install -c bioconda -c conda-forge chromap

cd /projectnb/paxlab/Projects/CodeSpaghetti/tools/ATX_epigenomics-main/fastq2frags/Refseq/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa 

```
  
Also has index generated by Yeting 

Original file names: 	D01942_NG05827_200403_linker2_R2.fastq.gz (32GB) 
	                    D01942_NG05827_200403_S1_L001_R1_001.fastq.gz (47GB)

From https://github.com/atlasxomics/ATX_epigenomics/blob/2af49aa081c5846ccc9fe1b868d4982430feed5c/fastq2frags/README.md
read1: genomic sequence
read2: linker1 | barcodeA | linker2 | barcodeB | genomic sequence

Going to rename files since they don't match 
D01942_NG05827_200403_linker2_R2.fastq.gz     -> D01942_NG05827_200403_R2.fastq.gz 
D01942_NG05827_200403_S1_L001_R1_001.fastq.gz -> D01942_NG05827_200403_R1.fastq.gz 
  
  
## Trim fastq 

look at script /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/src/01_trim_fastq.sh
  
## Making sam file 

look at script /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/src/02_map_fastq.sh


## Making bam file 

```{bash}
# module load sambamba/0.6.7
cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D01942_NG05827/lowseq_alignment/
  
module load samtools
samtools view -bS -@ 8 -o D01942_NG05827_200403_aln.bam D01942_NG05827_200403_aln.sam


samtools sort -@ 8 -o D01942_NG05827_200403_aln_sort.bam D01942_NG05827_200403_aln.bam && samtools index -@ 8 D01942_NG05827_200403_aln_sort.bam || { echo "BAM sorting or indexing FAILED."; exit 1; }

samtools flagstat -@ 8 D01942_NG05827_200403_aln_sort.bam > "D01942_NG05827_200403_aln_sort_flagstat.txt" || { echo "samtools flagstat FAILED."; exit 1; }
```


This isn't working out well, I don't have the right barcode files, so abandoning this right now!

# 2025-11-28 

Jeff found the cram file for the alignment, so will try monopgen on that now!

It is stored here: /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment/	419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.cram

```{bash}
module load samtools
cd /projectnb/paxlab/DATA/DriesSpatial/Atlasxomics/D1942_deepseq_alignment

samtools view -@ 16 -b -T Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -o 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.cram
```

2025-11-30 
Bam file has been created! now let's move on to variant call 


Looks like file is already sorted, so we need to generate index for bam file
```{bash}
module load sambamba 
sambamba index -t 8 --show-progress 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bam 419272-D01942_NG06549_AT-Z0005-CATGTATCCTCTGAT.bai
```


# Script to download the phased vcf 

```{bash}
#!/bin/bash
#$ -P paxlab        # Set SCC project to charge
#$ -pe omp 8       # Request cores
#$ -l h_rt=12:00:00  # Specify hard time limit for the job
#$ -N download       # Name job
#$ -o /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs
#$ -e /projectnb/paxlab/presh/src/Spatial_ATAC_analysis/qsub_logs
#$ -M preshita@bu.edu


# --- Configuration ---
MANIFEST_FILE="/projectnb/paxlab/presh/Data/variant_calling/phased_hg38_1000G_ref/phased-manifest_July2021.tsv"
# IMPORTANT: Replace this with the actual base URL where your files are hosted.
# Example: BASE_URL="https://example.com/data/"
BASE_URL="http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/" # <--- EDIT THIS LINE

# --- Script Start ---
echo "Starting download from manifest: $MANIFEST_FILE"
echo "Base URL: $BASE_URL"

# Check if wget or curl is available
if ! command -v wget &> /dev/null && ! command -v curl &> /dev/null; then
    echo "Error: Neither 'wget' nor 'curl' found. Please install one of them."
    exit 1
fi

# Loop through each line in the manifest file, extracting the filename
# We use 'awk' to get the first column (the filename)
while read -r line; do
    FILENAME=$(echo "$line" | awk '{print $1}')

    if [[ -z "$FILENAME" ]]; then # Skip empty lines
        continue
    fi

    FULL_URL="${BASE_URL}${FILENAME}"

    echo -e "\nDownloading: $FILENAME"
    echo "From: $FULL_URL"

    # --- Download the file ---
    # Use wget if available, otherwise fall back to curl
    if command -v wget &> /dev/null; then
        wget -c "$FULL_URL" # -c for continuing partial downloads
    elif command -v curl &> /dev_null; then
        curl -L -O "$FULL_URL" # -L to follow redirects, -O to use original filename
    fi

    if [[ $? -ne 0 ]]; then
        echo "ERROR: Download failed for $FILENAME."
    else
        echo "Download successful for $FILENAME."
    fi

done < "$MANIFEST_FILE"

echo -e "\nDownload process complete."
```


# Parallelizing Monopogen 

We can run germline variant calling on each chr separately to increase the speed 





  